# name: Build Rust

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     container:
#       image: rust:latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Install build env
#       run: ./scripts/installdeps.sh

#     - name: Build
#       run: ./scripts/buildNparse.sh

#     - name: Test
#       run: ./scripts/testNparse.sh
