name: Validate Workflow Syntax1

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - '.github/workflows/*.yml'

jobs:
  run-yaml-validation:
    uses: ./.github/workflows/run-validate.yml
